Console.Write("Ввведите первое число: ");
int x = Convert.ToInt32(Console.ReadLine());
Console.Write("Ввведите второе число: ");
int y = Convert.ToInt32(Console.ReadLine());
Console.Write("Ввведите третье число: ");
int z = Convert.ToInt32(Console.ReadLine());
int max = x;
if (y > max) max = y;
if (z > max) max = z;
Console.Write($"Максимальное число {max}");